version: "3"

services:
  app:
    build: ./app
    # volumes:
    #   - ./app:/usr/src/app
    #   - /usr/src/app/node_modules
    depends_on:
      - redis
    env_file:
      - ./app/.env
    expose:
      - "3000"

  redis:
    image: "redis:alpine"
    volumes:
      - redis:/data
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "4000:4000"

volumes:
  redis:
    driver: local
