version: '3'

services:
  api:
    build:
      dockerfile: ./docker/local/Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    environment:
      - PORT=3000
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:3000'

  redis:
    image: 'redis:alpine'
    volumes:
      - redis:/data
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s

volumes:
  redis:
    driver: local

